### ISSUE TITLE
Create custom normalizer?

### ISSUE THREAD

**Issue by icco** [13rac1/goldmark-wikilink#1]
Hi! This is great. I'm wondering how I pass in a custom normalizer though.

**Comment by 13rac1** [comment]
Thanks!

use WithNormalizer()
https://github.com/13rac1/goldmark-wikilink/blob/097c4b5ee51d70aa8cca574d5812b5dc979283d9/wikilink.go#L93-L97

**Comment by icco** [comment]
I'm not entirely sure how to provide a custom parser. Could you give an
example of how you're supposed to do this?

/Nat

**Comment by 13rac1** [comment]
Create a struct implementing the `FilenameNormalizer` interface and pass it to `WithNormalizer()`
https://github.com/13rac1/goldmark-wikilink/blob/097c4b5ee51d70aa8cca574d5812b5dc979283d9/wikilink.go#L68-L72
